### ISSUE TITLE
Some citations in short strong lensing section aren't bibtex

### ISSUE THREAD

**Issue by janewman-pitt-edu** [wadawson/Enabling-LSST-Dark-Energy-Science#19]
Phil, can you or someone from the SL group fix?

**Comment by drphilmarshall** [comment]
I'm on the case.

**Comment by drphilmarshall** [comment]
One of my bibtex entries had a badly formatted author field, sorry about that - that might have been the problem. I had to then make clean and make again to get a good build.

**Comment by janewman-pitt-edu** [comment]
Thanks, Phil!

jeff

**Comment by rmandelb** [comment]
Hi @drphilmarshall - I reopened this - I'm still seeing quite a few references that aren't bibtex and so don't show up in the refs.  For example in the first paragraph of sl_short.tex alone there are two of these (and more later in the section).  It has nothing to do with broken bibtex, because there's no bibtex involved.

**Comment by drphilmarshall** [comment]
Hmm. Did you `make clean` to get rid of the old .aux file? I just verified
that when I make a fresh clone, I can `make` the PDF just fine, and all
citations are correctly formatted.

On Tue, Jun 7, 2016 at 12:45 PM, Rachel Mandelbaum <notifications@github.com

**Comment by rmandelb** [comment]
I don't see how that's relevant?  Yes, the PDF short_version.pdf builds fine, but the point is that some of the references are hard-coded as text rather than as bibtex.  So that's not going to show up in any .aux file or give bibtex errors when compiling.  As I said, you can see it easily in the .tex file if you look in sl_short.tex, with two examples on lines 76-77, and several later on:
https://github.com/wadawson/Enabling-LSST-Dark-Energy-Science/blob/master/sl_short.tex

If @janewman-pitt-edu told us that we don't need to get all references bibtex'ed and into the reference section, and I missed it, then I guess this is fine as-is.  But I assumed that all references should be bibtex'ed so that everything shows up in the references, and these don't.

**Comment by drphilmarshall** [comment]
Ahhhh sorry, I understand now - yesterday I saw problems with the citations
not showing up properly, and it _was_ a bibtex problem, and I _did_ have to
do a make clean to solve it, but you are pointing out a new problem (or
perhaps an old one :-). Fixing it now. Thanks for your patience...

**Comment by rmandelb** [comment]
Thanks!
